"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MemberRoster.py']
DATA_FILES = ["Logo.png", "UserInterface.py"]
OPTIONS = {'packages':["openpyxl","requests","certifi"]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
